_wandb:
    value:
        cli_version: 0.21.0
        e:
            83ke4jl4yxiumkkjafr10jdd8h4304ms:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                args:
                    - --batch_size=128
                    - --dropout_rate=0.3
                    - --learning_rate=0.0001
                    - --lstm_units=[64, 32]
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "232573378560"
                email: gh003008@naver.com
                executable: /Users/gunhee/miniforge3/envs/torch-mps/bin/python
                host: LeegunhcBookAir
                memory:
                    total: "8589934592"
                os: macOS-14.4.1-arm64-arm-64bit
                program: /Users/gunhee/Documents/GitHub/project/main.py
                python: CPython 3.10.16
                root: /Users/gunhee/Documents/GitHub/project
                startedAt: "2025-07-14T12:48:13.554747Z"
                writerId: 83ke4jl4yxiumkkjafr10jdd8h4304ms
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 3
                - 8
                - 14
            "4": 3.10.16
            "5": 0.21.0
            "10":
                - 9
                - 17
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 128
dropout_rate:
    value: 0.3
learning_rate:
    value: 0.0001
lstm_units:
    value:
        - 64
        - 32
